[project]
name = "diffusinator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.2.3",
    "pillow>=11.1.0",
    "torch>=2.6.0",
]
